/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import Controle.Metodos;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author aluno
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();

        //Adicionar icone no programa
        URL url = this.getClass().getResource("/Img/favicon.png");  
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttAnimal = new javax.swing.JButton();
        bttVacina = new javax.swing.JButton();
        bttVeterinario = new javax.swing.JButton();
        bttVacinação = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnCadastro = new javax.swing.JMenu();
        JmCadAnimal = new javax.swing.JMenuItem();
        JmCadVacina = new javax.swing.JMenuItem();
        JmCadVeterinario = new javax.swing.JMenuItem();
        MnProcesso = new javax.swing.JMenu();
        JmVacinacao = new javax.swing.JMenuItem();
        MNConfiguracao = new javax.swing.JMenu();
        JMConexao = new javax.swing.JMenuItem();
        JMBancodedados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System Veterinaria");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(557, 378));
        setName("FormPrincipal"); // NOI18N
        getContentPane().setLayout(null);

        bttAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bttAnimal.png"))); // NOI18N
        bttAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAnimalActionPerformed(evt);
            }
        });
        getContentPane().add(bttAnimal);
        bttAnimal.setBounds(10, 11, 73, 78);

        bttVacina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bttVacina.png"))); // NOI18N
        bttVacina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVacinaActionPerformed(evt);
            }
        });
        getContentPane().add(bttVacina);
        bttVacina.setBounds(89, 11, 73, 78);

        bttVeterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/veterinarian.png"))); // NOI18N
        bttVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVeterinarioActionPerformed(evt);
            }
        });
        getContentPane().add(bttVeterinario);
        bttVeterinario.setBounds(250, 10, 80, 78);

        bttVacinação.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bttVacinacao.png"))); // NOI18N
        bttVacinação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVacinaçãoActionPerformed(evt);
            }
        });
        getContentPane().add(bttVacinação);
        bttVacinação.setBounds(168, 11, 73, 78);

        MnCadastro.setText("Cadastro");

        JmCadAnimal.setText("Cadastro de Animal");
        JmCadAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmCadAnimalActionPerformed(evt);
            }
        });
        MnCadastro.add(JmCadAnimal);

        JmCadVacina.setText("Cadastro de Vacina");
        JmCadVacina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmCadVacinaActionPerformed(evt);
            }
        });
        MnCadastro.add(JmCadVacina);

        JmCadVeterinario.setText("Cadastro de Veterinário");
        MnCadastro.add(JmCadVeterinario);

        jMenuBar1.add(MnCadastro);

        MnProcesso.setText("Processo");

        JmVacinacao.setText("Vacinação");
        JmVacinacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmVacinacaoActionPerformed(evt);
            }
        });
        MnProcesso.add(JmVacinacao);

        jMenuBar1.add(MnProcesso);

        MNConfiguracao.setText("Configuração");

        JMConexao.setText("Conexão Banco de dados");
        JMConexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMConexaoActionPerformed(evt);
            }
        });
        MNConfiguracao.add(JMConexao);

        JMBancodedados.setText("Criar Banco de dados");
        JMBancodedados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMBancodedadosActionPerformed(evt);
            }
        });
        MNConfiguracao.add(JMBancodedados);

        jMenuBar1.add(MNConfiguracao);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(557, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JmCadVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmCadVacinaActionPerformed
        FormVacina CadastroVacina = new FormVacina();
        CadastroVacina.setVisible(true);
    }//GEN-LAST:event_JmCadVacinaActionPerformed

    private void JmCadAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmCadAnimalActionPerformed
        
        FormAnimal CadastroAnimal = new FormAnimal();
        CadastroAnimal.setVisible(true);
    }//GEN-LAST:event_JmCadAnimalActionPerformed

    private void bttAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAnimalActionPerformed
        FormAnimal CadastroAnimal = new FormAnimal();
        CadastroAnimal.setVisible(true);
    }//GEN-LAST:event_bttAnimalActionPerformed

    private void bttVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVacinaActionPerformed
        FormVacina CadastroVacina = new FormVacina();
        CadastroVacina.setVisible(true);
    }//GEN-LAST:event_bttVacinaActionPerformed

    private void JmVacinacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmVacinacaoActionPerformed

        FormVacinacao Vacinacao = new FormVacinacao();
        Vacinacao.setVisible(true);
    }//GEN-LAST:event_JmVacinacaoActionPerformed

    private void bttVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttVeterinarioActionPerformed

    private void JMConexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMConexaoActionPerformed
       
               FormConexao Conexao = new FormConexao();
                
               Conexao.setVisible(true);
        

    }//GEN-LAST:event_JMConexaoActionPerformed

    private void bttVacinaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVacinaçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttVacinaçãoActionPerformed

    private void JMBancodedadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMBancodedadosActionPerformed

        FormBanco Banco = new FormBanco();
        Banco.setVisible(true);
    }//GEN-LAST:event_JMBancodedadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="cbttAnimal" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMBancodedados;
    private javax.swing.JMenuItem JMConexao;
    private javax.swing.JMenuItem JmCadAnimal;
    private javax.swing.JMenuItem JmCadVacina;
    private javax.swing.JMenuItem JmCadVeterinario;
    private javax.swing.JMenuItem JmVacinacao;
    private javax.swing.JMenu MNConfiguracao;
    private javax.swing.JMenu MnCadastro;
    private javax.swing.JMenu MnProcesso;
    private javax.swing.JButton bttAnimal;
    private javax.swing.JButton bttVacina;
    private javax.swing.JButton bttVacinação;
    private javax.swing.JButton bttVeterinario;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
